### ISSUE TITLE
Idea: Primary intent and Secondary Intent

### ISSUE THREAD

**Issue by kvnper** [5axes/UniversalCuraSettings#20]
It's probably a long, long way off, but something I think would be a good idea is an option to specify a secondary intent that, where allowed, complements the primary intent. Like a second priority intent.

**Comment by 5axes** [comment]
Yes could be.  Right now we can do something like that by setting two intent like :

Mechanical Part -> Small Part

Or

Mechanical Part -> Prototype

![image](https://user-images.githubusercontent.com/11015345/132678313-c9676dc9-6d27-410a-91cf-bd07343267c8.png)

Apply then
![image](https://user-images.githubusercontent.com/11015345/132678429-2d7833ad-e8c3-4be1-bd92-1e0ae69f1a85.png)

**Comment by kvnper** [comment]
Oh very good. I imagine there will be some conflicts or incompatibility in
certain situations

**Comment by 5axes** [comment]
Yes for sure, that's why I haven't released on the Cura marketplace for the moment. The idea of this plugin is to preconized some settings according to some intent or specific case. Something similar as the recommendations that un expert can make on a forum when someone is asking  the right settings for a material or to solved an issue.  So it should be not so accurate as a profile, but much more generic. The advantage of using a code and not a profil is the possibility to use condition case  ( if .. then .. else )  but of course sometimes you could use some values not suitable   for every printers or you can have conflict between modification.

**Comment by 5axes** [comment]
https://github.com/5axes/UniversalCuraSettings/wiki/How-to-use-It
